### ISSUE TITLE
Is this repo still relevant?

### ISSUE THREAD

**Issue by mlainez** [smartrent/elixir_flutter_embedder#11]
Hi there, following an interaction with @fhunleth in the nerves system rpi4 repo, I've been looking into running Flutter on nerves and stumbled upon this.

However, I can't figure out how to make it work on both main and updates branch. I'm guessing this is not the most recent way to do things so I was wondering if there were any pointers I should follow to figure it out.

Thanks!

**Comment by fhunleth** [comment]
There are pieces we need to open source. However, https://github.com/smartrent/flutter-pi is what we use in production.

**Comment by mlainez** [comment]
@fhunleth thanks, I noticed it was present in buildroot but that it required systemd... I'll see what I can do by myself.

**Comment by fhunleth** [comment]
This might be useful. [smrt-flutter-pi.tgz](https://github.com/smartrent/elixir_flutter_embedder/files/15130578/smrt-flutter-pi.tgz)
